### ISSUE TITLE
tarpaulin installation is broken

### ISSUE THREAD

**Issue by jplatte** [taiki-e/install-action#167]
Since today, the following CI step is consistently [failing](https://github.com/matrix-org/matrix-rust-sdk/actions/runs/5680145335/job/15393680800?pr=2340):

```yml
    - name: Install tarpaulin
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-tarpaulin
```

with the error

```
info: verifying sha256 checksum for cargo-tarpaulin-x86_64-unknown-linux-musl.tar.gz
sha256sum: WARNING: 1 computed checksum did NOT match
```
