### ISSUE TITLE
[bug] Cargo not found

### ISSUE THREAD

**Issue by melMass** [taiki-e/install-action#500]
Hi,

In a CI where I don't need Rust but some rust binaries I wanted to use this action but following the fallback approach, i.e:

```yaml
    - uses: taiki-e/install-action@v2
      with:
        tool: exa,ripgrep,coreutils,fd-find
```

It fails as it tries to call `cargo binstall` and not `cargo-binstall`. I tried the "official" binstall action but it doesn't add the bin path to PATH and I couldn't find a reliable way to do it cross runners.

Is there a better way?

Thanks
